### ISSUE TITLE
Sample native scripted metric aggrgation

### ISSUE THREAD

**Issue by Vineeth-Mohan** [imotov/elasticsearch-native-script-example#12]
It would be useful if you could accommodate sample java code which can do scripted metric aggregation

**Comment by imotov** [comment]
@Vineeth-Mohan do you have any particular script in mind?

**Comment by Vineeth-Mohan** [comment]
@imotov  - If you can translate the example given here into  a native java code , that would be good enough - https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-scripted-metric-aggregation.html
