### ISSUE TITLE
How to lookup a date field?

### ISSUE THREAD

**Issue by jnfeinstein** [imotov/elasticsearch-native-script-example#15]
Any chance someone could add an example on working with date fields? 

There isn't a lot of documentation for building native plugins outside of this project.  `ScriptDocValues` doesn't contain a `.Date` class.  Some other stale examples suggested it can be casted to a `Longs`, someone said it didn't work, and then the trail went dead.

Any pointers would be most appreciated!

**Comment by imotov** [comment]
@jnfeinstein  Dates are stored as longs internally. So, using `Longs` should work. It even has a special method [getDate](https://github.com/elastic/elasticsearch/blob/1.7/src/main/java/org/elasticsearch/index/fielddata/ScriptDocValues.java#L134) to convert the retrieved long value into a date. Which version of elasticsearch are you using? What error do you get when you try to use Longs? Could you show your non-working example by any chance?

**Comment by jnfeinstein** [comment]
Everything you said worked perfectly.  I'd forgotten that dates are technically longs.  Thanks for being #1 source of native scripting voodoo knowledge.
