### ISSUE TITLE
Could not find plugin descriptor 'plugin-descriptor.properties'

### ISSUE THREAD

**Issue by rickyhiga** [imotov/elasticsearch-native-script-example#16]
I used your source of the 2.0 branch.
For build the project i changed "2.0.0-beta2-SNAPSHOT" to "2.0.0" in the POM and this is the result:
<parent>
        <groupId>org.elasticsearch.plugin</groupId>
        <artifactId>plugins</artifactId>
        <version>2.0.0</version>
    </parent>

    <name>elasticsearch-native-script-example</name>
    <groupId>org.elasticsearch.plugin</groupId>
    <artifactId>elasticsearch-native-script-example</artifactId>
    <version>2.0.0</version>
    <description>ElasticSearch Plugin with Native Script Examples</description>
    <inceptionYear>2013</inceptionYear>
...

The build was successful but when i tried to install the plugin that's happened: 
/usr/share/elasticsearch/bin/plugin install file:./target/elasticsearch-native-script-example-2.0.0.jar 
-> Installing from file:./target/elasticsearch-native-script-example-2.0.0.jar...
Trying file:./target/elasticsearch-native-script-example-2.0.0.jar ...
Downloading .DONE
Verifying file:./target/elasticsearch-native-script-example-2.0.0.jar checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by imotov** [comment]
Just tried with 59be447dcf3bbaf4658858f143e4e74eb2d7116d. Everything seem to work fine. You just need to install .zip file instead of .jar file. Try installing `target/releases/elasticsearch-native-script-example-2.0.0.zip`

**Comment by rickyhiga** [comment]
Thank you and sorry for the wasted time, you are right!
