### ISSUE TITLE
Differenciate plugin version and ES parent plugin version

### ISSUE THREAD

**Issue by YannBrrd** [imotov/elasticsearch-native-script-example#17]
Hi @imotov,

Is there an easy way to differentiate ES parent plugin version and plugin version ? 

Thanks.
Yann

**Comment by imotov** [comment]
@YannBrrd yes, plugin can have any version you want, the important part is that plugin descriptor contains the version that you are targeting. In this example both version are tied for simplicity.

**Comment by YannBrrd** [comment]
Do you have somewhere an exemple of plugin descriptor ? I have it generated through pom.xml as of now. Can I just add a property in [pom.xml](https://github.com/YannBrrd/elasticsearch-entity-resolution/blob/master/pom.xml)

**Comment by imotov** [comment]
I have added an example of using an alternative version (`5.3.0.0` vs `5.3.0`) to master.
