### ISSUE TITLE
question compiling

### ISSUE THREAD

**Issue by YunchaoGongSC** [imotov/elasticsearch-native-script-example#18]
Hello

When we download it and try to compile, we got the following error. Is there a way to fix it? Thanks!

[ERROR] Failed to execute goal on project elasticsearch-native-script-example: Could not resolve dependencies for project org.elasticsearch.plugin:elasticsearch-native-script-example:jar:3.0.0-SNAPSHOT: Failed to collect dependencies at org.elasticsearch:elasticsearch:jar:tests:3.0.0-SNAPSHOT -> org.apache.lucene:lucene-grouping:jar:5.5.0-snapshot-1719088: Failed to read artifact descriptor for org.apache.lucene:lucene-grouping:jar:5.5.0-snapshot-1719088: Could not transfer artifact org.apache.lucene:lucene-grouping:pom:5.5.0-snapshot-1719088 from/to elasticsearch-releases (http://maven.elasticsearch.org/releases): Not authorized , ReasonPhrase:Unauthorized. -> [Help 1]

**Comment by imotov** [comment]
Yes, the current master version is broken. The elasticsearch master switched from maven to gradle and I didn't have a chance to update the project. I hope to get to it during holidays. Which version of elasticsearch are you targeting?

**Comment by YunchaoGongSC** [comment]
Thanks for the very quick responding! 

For ES 2.1.0, I tried to change <version> to  2.1.0, and removed some code that does not compile, and it seems it worked.

Will <version> 2.1.0 work for ES 2.1.0 ? Thanks!

**Comment by imotov** [comment]
Yes, it looks like there are some changes in 2.1 that I need to incorporate as well. So, at the moment only 2.0 and 1.x branches work. Sorry, didn't have much time for the side projects lately.

**Comment by YunchaoGongSC** [comment]
Oh, I mean I changed the version parameter in this project from 3.0.0 to 2.1.0. Will this change be compatible with ES 2.1.0? Thanks!

**Comment by YunchaoGongSC** [comment]
This project is great!

**Comment by imotov** [comment]
No, that's not going to work. There were some changes in 2.1 that make the current code incompatible with 2.1.0 and above. As I said above I need to update the example to work with 2.1 and unfortunately it involves more than just changing the version.

**Comment by YunchaoGongSC** [comment]
Thanks! Are you aware of any documentation that we can look into to develop
plugins?

**Comment by imotov** [comment]
I am not aware of any documentation besides this [page](https://www.elastic.co/guide/en/elasticsearch/plugins/current/plugin-authors.html). Plugins are very tightly integrated with elasticsearch code. So, I think the best way to develop plugins is by looking at elasticsearch source code and examples of plugins that are part elasticsearch project.

**Comment by YunchaoGongSC** [comment]
Thanks! Do you mean even if we want to implement some very basic plugins,
we need to use SNAPSHOT-3.0.0 and use gradle to compile?

**Comment by imotov** [comment]
If you want your plugin to run with elasticsearch 3.0.0-SNAPSHOT you should compile it with 3.0.0-SNAPSHOT. If you need to use it with 2.1.0 you need to compile it with 2.1.0.

**Comment by YunchaoGongSC** [comment]
Oh great! So I thought we had a misunderstanding before :)

We are running ES 2.1.0, so using plugin version 2.1.0 should be good!

**Comment by YunchaoGongSC** [comment]
One more question, when I try to compile the code after changing version to 2.1.0, I got one issue cannot be resolved. For the following line

final Node node = new MockNode(settings, Version.CURRENT, Collections.singletonList(NativeScriptExamplesPlugin.class));


It is passing Collections.singletonList(NativeScriptExamplesPlugin.class)) to Collection<Class<? extends Plugin>>, and it seems the syntax is legit. However, both my editor and maven gives error for this line. Is there any particular setup I need to do to compile this?

Thanks!

**Comment by imotov** [comment]
@YunchaoGongSC I pushed 2.1 branch that should work with elasticsearch 2.1.1. I am still working on the master branch.

**Comment by imotov** [comment]
@YunchaoGongSC I have updated the master branch to work with elasticsearch master (3.0.0-SNAPSHOT). The master branch is now using gradle.

**Comment by YunchaoGongSC** [comment]
Thank you so much Imotov!
