### ISSUE TITLE
question about script window_size

### ISSUE THREAD

**Issue by YunchaoGongSC** [imotov/elasticsearch-native-script-example#19]
Hey @imotov 

Thanks for your help before! Have one more question, in your script 
https://github.com/imotov/elasticsearch-native-script-example/blob/master/example/termscoring.sh#L64
is there a way to add a window_size for reranking within each shard? In regular "rescore" part, we can always add a "window_size": 100 to restrict the data points being ranked within each shard. Is there a way to add such a parameter in "script_score" ? Thanks!

**Comment by imotov** [comment]
@YunchaoGongSC let's leave github issues for bug reports and feature requests. The Elastic [discussion forum](https://discuss.elastic.co/) is much better place to ask questions like this. Saying that, you can always wrap a `function_score` query into a `rescore` query
