### ISSUE TITLE
"script_score query does not support [params]"-es 5.3.1

### ISSUE THREAD

**Issue by guoxiaolu** [imotov/elasticsearch-native-script-example#30]
I wanna test cosing similarity of termscoring.sh, but returns error as title. I have google some answers, it seems that this is a es error (but author said it is fixed) I don't know whether this example can run or not  in es 5.3.1 version

**Comment by imotov** [comment]
Sorry, I didn't port any scoring examples to 5.3. If you want to work with similarity you should, probably, look into implementing your own `SimilarityProvider` instead of using score. Meanwhile, I am going to remove obsolete and update current examples.

**Comment by guoxiaolu** [comment]
Tks, good job. This project is helpful for me
